library(iRefR)
library(GEOquery)
library(Biobase)
library(org.Hs.eg.db)
library(TCGAbiolinks)
samplesList=c("TCGA-BH-A0H7-11A-13R-A089-07","TCGA-BH-A0H7-01A-13R-A056-07")
query <- TCGAquery(samples = samplesList,platform = "AgilentG4502A_07_3",level = 3)
TCGAdownload(query, path = "/tmp/dataBrca",samples = samplesList)
expressionDataTCGA <- data.frame(TCGAprepare(query, dir = "/tmp/dataBrca",summarizedExperiment = F))
gds = getGEO('GDS3837',AnnotGPL = TRUE, getGPL = TRUE,destdir = "/tmp")
gpl = getGEO(Meta(gds)$platform,destdir = "/tmp")
eset = GDS2eSet(gds, GPL=gpl,do.log2=FALSE)
numPairs = dim(pData(eset))[1]/2
expressionDataGEO=prepareExpressionData(eset,gpl,probeCombinerMean)
iref_mitab=get_irefindex(tax_id="9606",data_folder="/tmp/",iref_version = "13.0")
irefPPIGraph = createIGraphObject(getGeneInteractionListFromIRefMITAB(iref_mitab))
us=getUniProtToHGNCSymbolMapping();
reactome_mitab= downloadReactomeInteractions(data_folder="/tmp/")
reactomePPIGraph=createIGraphObject(getGeneInteractionListFromReactomeMITAB(reactome_mitab))
reactome_pdata = downloadReactomePathways("/tmp",'HomoSapiens')
reactomePathwayData=loadPathwayDataReactome(reactome_pdata,us)
experimentDataGEO=runTestOnData(expressionDataGEO,1:60,61:120,logPairedTTestFunction)
experimentDataTCGA=runTestOnData(tcgaData,1,2,foldChangeFunction,list(exponent=2))
personalizationVectorsGEO=computePersonalizationVectors(experimentDataGEO,reactomePPIGraph,data.frame(foldChange=1,pValue=1),outdegreeNormalizedFCOneMinusPScoreFunction)
personalizationVectorsTCGA=computePersonalizationVectors(experimentDataTCGA,reactomePPIGraph,data.frame(foldChange=1),outdegreeNormalizedFCScoreFunction)
pageRanksGEO=computePageRanks(personalizationVectorsGEO,reactomePPIGraph,0.7)
pageRanksTCGA=computePageRanks(personalizationVectorsTCGA,reactomePPIGraph,0.7)
pathwayScoresGEO=computePathwayScores(pageRanksGEO,reactomePathwayData$pathwayMembership,meanAbsoluteDeviationDistanceFunction,list())
pathwayScoresTCGA=computePathwayScores(pageRanksTCGA,reactomePathwayData$pathwayMembership,meanAbsoluteDeviationDistanceFunction,list())
resultGEO=cbind(reactomePathwayData$pathwayInfo,pathwayScoresGEO)
resultTCGA=cbind(reactomePathwayData$pathwayInfo,pathwayScoresTCGA)
resultGEO=resultGEO[with(resultGEO,order(-meanAbsoluteDeviation)),]
resultTCGA=resultTCGA[with(resultTCGA,order(-meanAbsoluteDeviation)),]
